// <auto-generated />
using System;
using Ev_tapsirigi_ORM3.DbContex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ev_tapsirigi_ORM3.Migrations
{
    [DbContext(typeof(E_commerceContextDb))]
    partial class E_commerceContextDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.CustomerAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

<<<<<<< HEAD
                    b.Property<int?>("CustomerId")
=======
                    b.Property<int>("CustomerId")
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
<<<<<<< HEAD
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");
=======
                        .IsUnique();
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431

                    b.ToTable("CustomerAdress");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<< HEAD
                    b.Property<int?>("CustomerId")
=======
                    b.Property<int>("CustomerId")
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

<<<<<<< HEAD
                    b.Property<int?>("CategoryId")
=======
                    b.Property<int>("CategoryId")
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Price", "[Price] > 0");
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.CustomerAdress", b =>
                {
                    b.HasOne("Ev_tapsirigi_ORM3.Table.Customer", "Customer")
                        .WithOne("CustomerAdress")
<<<<<<< HEAD
                        .HasForeignKey("Ev_tapsirigi_ORM3.Table.CustomerAdress", "CustomerId");
=======
                        .HasForeignKey("Ev_tapsirigi_ORM3.Table.CustomerAdress", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Order", b =>
                {
                    b.HasOne("Ev_tapsirigi_ORM3.Table.Customer", "Customer")
                        .WithMany("Orders")
<<<<<<< HEAD
                        .HasForeignKey("CustomerId");
=======
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Product", b =>
                {
                    b.HasOne("Ev_tapsirigi_ORM3.Table.Category", "Category")
                        .WithMany("Products")
<<<<<<< HEAD
                        .HasForeignKey("CategoryId");
=======
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("Ev_tapsirigi_ORM3.Table.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ev_tapsirigi_ORM3.Table.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ev_tapsirigi_ORM3.Table.Customer", b =>
                {
<<<<<<< HEAD
                    b.Navigation("CustomerAdress");
=======
                    b.Navigation("CustomerAdress")
                        .IsRequired();
>>>>>>> 7a11ef8b01370e9921aaa3916126769e16030431

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
